#pragma once

#define PROG_LED_PIN 1
#define PROG_LED_PIN_ACTIVE_ON HIGH
#define PROG_BUTTON_PIN 0
#define PROG_BUTTON_PIN_INTERRUPT_ON FALLING
// #define SAVE_INTERRUPT_PIN 22
#define KNX_UART_RX_PIN 17
#define KNX_UART_TX_PIN 16
#define PLAYER_UART_RX_PIN 9
#define PLAYER_UART_TX_PIN 8

// #define PROG_LED_PIN 21
// #define PROG_LED_PIN_ACTIVE_ON HIGH
// #define PROG_BUTTON_PIN 22
// #define PROG_BUTTON_PIN_INTERRUPT_ON FALLING
// #define SAVE_INTERRUPT_PIN 20 // 8
// #define INFO_LED_PIN 38
// #define INFO_LED_PIN_ACTIVE_ON HIGH
// #define KNX_UART_RX_PIN 1
// #define KNX_UART_TX_PIN 0
// #define PLAYER_UART_RX_PIN 5
// #define PLAYER_UART_TX_PIN 4